name: Tests

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - name: Composer
        run: composer install --no-progress --no-interaction
      - name: PHPUnit Tests
        run: vendor/bin/phpunit --configuration phpunit.xml
